### ISSUE TITLE
Error: The codeframe formatter is no longer part of core ESLint.

### ISSUE THREAD

**Issue by mizdra** [mizdra/eslint-interactive#77]
log:

```
✔ What format do you want to display the problem message in? · withPager
Error: The codeframe formatter is no longer part of core ESLint. Install it manually with `npm install -D eslint-formatter-codeframe`
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    ...
```

**Comment by mizdra** [comment]
- eslint-formatter-codeframe is a formatter for eslint
- eslint-interactive uses it to display error messages.
- The formatter is included in the dependencies of eslint-interactive.
  - So it's strange to get an error about eslint-formatter-codeframe not being found
- I will investigate the cause of the problem.

**Comment by mizdra** [comment]
- It seems that the problem is reproduced when eslint-interactive is installed globally and eslint is installed locally.
- To solve the problem, we might need to consider the following approach.
  - Install both eslint-interactive and eslint globally
  - Install both eslint-interactive and eslint locally

**Comment by mizdra** [comment]
- Many projects that use eslint-interactive use a local installation of eslint.
- Therefore, it is best to install eslint-interactive locally as well.
- So, we want to warn the user when the eslint-interactive is started from a global installation.

**Comment by mizdra** [comment]
FYI: A typical example of a development support tool that is recommended for local installation is webpack-bundle-analyzer.

**Comment by mizdra** [comment]
I came up with a way to fix this error.

**Comment by mizdra** [comment]
Maybe it's fixed 🎉
